[build]
  publish = "dist" # Vite outputs the built files to the 'dist' directory
  command = "npm run build" # Command to build the Vite frontend

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
